// resources/apps/admin/components/ui/button/button.vue
<script setup>
	import { buttonVariants } from '.';

	const { variant, size, icon, ...props } = defineProps({
		variant: {
			type: String,
			default: 'primary',
			validator: (value) => ['primary', 'secondary', 'tertiary', 'ghost', 'danger'].includes(value),
		},
		size: {
			type: String,
			default: 'md',
			validator: (value) => ['sm', 'md', 'lg'].includes(value),
		},
		icon: {
			type: Boolean,
			default: false,
		},
		type: {
			type: String,
			default: 'button',
			validator: (value) => ['button', 'submit', 'reset'].includes(value),
		},
		class: {
			type: String,
			default: '',
		},
		disabled: {
			type: Boolean,
			default: false,
		},
	});

	const emit = defineEmits(['click']);
</script>

<template>
	<button :class="buttonVariants({ variant, size, icon })" v-bind="props" @click="emit('click')">
		<slot />
	</button>
</template>

<style lang="postcss">
	.btn {
		@apply inline-flex h-9 items-center justify-center gap-2.5 rounded-md px-3 py-1.5 text-sm font-medium leading-none transition-[background,color,border] duration-200 disabled:cursor-not-allowed disabled:text-muted-foreground disabled:opacity-60;

		&.btn-primary {
			@apply bg-primary text-primary-foreground hover:bg-primary/80 disabled:hover:bg-primary;
		}

		&.btn-secondary {
			@apply bg-secondary text-secondary-foreground hover:bg-secondary/80 disabled:hover:bg-secondary;
		}

		&.btn-tertiary {
			@apply border border-accent bg-muted text-muted-foreground hover:bg-muted/80 disabled:hover:bg-muted;
		}

		&.btn-ghost {
			@apply bg-transparent text-foreground hover:bg-accent/80 disabled:hover:bg-transparent;
		}

		&.btn-danger {
			@apply bg-destructive text-destructive-foreground hover:bg-destructive/80 disabled:hover:bg-destructive;
		}

		&.btn-small {
			@apply h-8 px-2.5 py-1;
		}

		&.btn-large {
			@apply h-10 px-4 py-2.5;
		}

		&.btn-icon {
			@apply w-9 p-0 text-lg;

			&.btn-small {
				@apply w-8;
			}

			&.btn-large {
				@apply w-10;
			}
		}

		&.btn-full {
			@apply w-full;
		}
	}
</style>

// frontend/admin/components/ui/button.tsx
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';

import { cn } from '~/lib/utils';

type Props = React.ComponentProps<'button'> &
	VariantProps<typeof buttonVariants> & {
		asChild?: boolean;
	};

const buttonVariants = cva(
	'inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 text-sm leading-none font-medium whitespace-nowrap transition-[color,background] duration-200 outline-none disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive icon-child:pointer-events-none',
	{
		variants: {
			variant: {
				default:
					'bg-primary text-primary-foreground hover:bg-primary/80',
				secondary:
					'bg-accent text-accent-foreground hover:bg-accent/80',
				destructive:
					'bg-destructive text-white hover:bg-destructive/80 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40',
				outlined:
					'border border-primary/30 bg-transparent text-primary hover:bg-muted',
				ghost: 'hover:bg-muted hover:text-foreground',
				link: 'text-primary underline underline-offset-4',
			},
			size: {
				default: 'h-9 px-4.5 icon-child:text-lg',
				sm: 'h-8 px-4 icon-child:text-base',
				lg: 'h-10 px-5 icon-child:text-lg',
				icon: 'size-9',
			},
		},
		defaultVariants: {
			variant: 'default',
			size: 'default',
		},
	},
);

const Button = ({
	className,
	variant,
	size,
	asChild = false,
	...props
}: Props) => {
	const Comp = asChild ? Slot : 'button';

	return (
		<Comp
			data-slot="button"
			className={cn(buttonVariants({ variant, size, className }))}
			{...props}
		/>
	);
};

export { Button, buttonVariants };
