// resources/apps/admin/components/ui/sidebar/sidebar.vue
<script setup>
	import { inject } from 'vue';

	import { cn } from '@/js/lib/utils';
	import SidebarContent from './sidebar-content.vue';
	import SidebarFooter from './sidebar-footer.vue';
	import SidebarHeader from './sidebar-header.vue';
	import SidebarOverlay from './sidebar-overlay.vue';

	const { toggle } = inject('sidebar');
</script>

<template>
	<aside
		:class="
			cn(
				'fixed top-0 left-0 z-50 size-full max-w-75 overflow-hidden border-r border-border bg-card transition-[max-width] duration-200 lg:relative',
				!toggle && 'max-w-0',
			)
		"
	>
		<div class="grid h-full w-75 grid-rows-[auto_1fr_auto]">
			<SidebarHeader>
				<slot name="header" />
			</SidebarHeader>
			<SidebarContent>
				<slot />
			</SidebarContent>
			<SidebarFooter>
				<slot name="footer" />
			</SidebarFooter>
		</div>
	</aside>
	<SidebarOverlay />
</template>

// frontend/admin/components/ui/sidebar.tsx
import { SidebarIcon } from 'lucide-react';
import { createContext, useContext } from 'react';

import { useSidebarStore } from '@/admin/context/sidebar';
import { Button } from './button';
import { cn } from '~/lib/utils';
import {
	SidebarHeaderProps,
	SidebarProps,
	SidebarProviderProps,
} from '@/admin/types/sidebar';

const SidebarContext = createContext<ReturnType<typeof useSidebarStore> | null>(
	null,
);

const useSidebar = () => {
	const context = useContext(SidebarContext);
	if (!context)
		throw new Error('useSidebar must be used within a SidebarProvider');

	return context;
};

const SidebarProvider = ({
	open,
	defaultOpen,
	onOpenChange,
	children,
}: SidebarProviderProps) => {
	const store = useSidebarStore({
		open,
		defaultOpen,
		onOpenChange,
	});

	return (
		<SidebarContext.Provider value={store}>
			<div
				className={cn('group/wrapper grid size-full grid-cols-sidebar')}
			>
				{children}
			</div>
		</SidebarContext.Provider>
	);
};

const Sidebar = ({ variant = 'default', children }: SidebarProps) => {
	const { state } = useSidebar();

	return (
		<aside
			className="group/sidebar relative size-full max-w-sidebar overflow-hidden bg-sidebar-background text-sidebar-foreground transition-[max-width] duration-250"
			data-state={state}
			data-variant={variant}
		>
			<div className="relative h-full w-sidebar transition-[width] duration-250"></div>
			<div
				className={cn(
					'fixed top-0 left-sidebar z-0 h-full w-sidebar border-r border-sidebar-border transition-[width,left] duration-250',
				)}
			>
				{children}
			</div>
		</aside>
	);
};

const SidebarTrigger = () => {
	const { toggle } = useSidebar();

	return (
		<Button variant="ghost" size="icon" className="size-9" onClick={toggle}>
			<SidebarIcon className="size-5" />
		</Button>
	);
};

const SidebarHeader = ({ className, children }: SidebarHeaderProps) => (
	<div className={cn('h-16 border-b border-sidebar-border', className)}>
		{children}
	</div>
);

export { SidebarProvider, Sidebar, SidebarTrigger, SidebarHeader };
