// resources/admin/layouts/admin.tsx
import { AppSidebar } from '../components/layout/sidebar';
import { Topbar } from '../components/layout/topbar';
import { SidebarProvider } from '../components/ui/sidebar';
import { cn } from '@/admin/lib/utils';

type Props = {
	children?: React.ReactNode;
	className?: string;
};

export const AdminLayout = ({ children, className }: Props) => {
	return (
		<SidebarProvider variant="compact">
			<AppSidebar />
			<div className="grid size-full grid-rows-[auto_1fr_auto]">
				<Topbar />
				<main className={cn('container p-8', className)}>{children}</main>
				<footer></footer>
			</div>
		</SidebarProvider>
	);
};

// resources/apps/admin/layout/admin.vue
<script setup>
	import { Toaster } from '@/admin/components/ui/sonner';
	import { cn } from '@/js/lib/utils';
	import { SidebarProvider } from '../components/ui/sidebar';
	import Sidebar from './sidebar.vue';
	import Topbar from './topbar.vue';

	const props = defineProps({
		class: {
			type: String,
			default: '',
		},
		links: {
			type: Array,
			default: () => [],
		},
	});
</script>

<template>
	<SidebarProvider>
		<Sidebar />
		<div class="layout">
			<Topbar :links="props.links" />
			<main :class="cn('container mx-auto p-8', props.class)">
				<slot />
			</main>
			<footer></footer>
		</div>
	</SidebarProvider>
	<Toaster />
	<div id="modal-root"></div>
</template>
