// frontend/admin/components/ui/button.tsx
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';

import { cn } from '~/lib/utils';

type Props = React.ComponentProps<'button'> &
	VariantProps<typeof buttonVariants> & {
		asChild?: boolean;
	};

const buttonVariants = cva(
	'inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 text-sm leading-none font-medium whitespace-nowrap transition-[color,background] duration-200 outline-none disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive icon-child:pointer-events-none',
	{
		variants: {
			variant: {
				default:
					'bg-primary text-primary-foreground hover:bg-primary/80',
				secondary:
					'bg-accent text-accent-foreground hover:bg-accent/80',
				destructive:
					'bg-destructive text-white hover:bg-destructive/80 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40',
				outlined:
					'border border-primary/30 bg-transparent text-primary hover:bg-muted',
				ghost: 'hover:bg-muted hover:text-foreground',
				link: 'text-primary underline underline-offset-4',
			},
			size: {
				default: 'h-9 px-4.5 icon-child:text-lg',
				sm: 'h-8 px-4 icon-child:text-base',
				lg: 'h-10 px-5 icon-child:text-lg',
				icon: 'size-9',
			},
		},
		defaultVariants: {
			variant: 'default',
			size: 'default',
		},
	},
);

const Button = ({
	className,
	variant,
	size,
	asChild = false,
	...props
}: Props) => {
	const Comp = asChild ? Slot : 'button';

	return (
		<Comp
			data-slot="button"
			className={cn(buttonVariants({ variant, size, className }))}
			{...props}
		/>
	);
};

export { Button, buttonVariants };

// resources/apps/root/components/ui/button/button.vue
<script setup>
	import { buttonVariants } from '.';

	const { variant, size, icon, ...props } = defineProps({
		variant: {
			type: String,
			default: 'primary',
			validator: (value) => ['primary', 'secondary', 'ghost', 'danger'].includes(value)
		},
		size: {
			type: String,
			default: 'md',
			validator: (value) => ['sm', 'md', 'lg'].includes(value)
		},
		icon: {
			type: Boolean,
			default: false
		},
		type: {
			type: String,
			default: 'button',
			validator: (value) => ['button', 'submit', 'reset'].includes(value)
		},
		class: {
			type: String,
			default: ''
		},
		disabled: {
			type: Boolean,
			default: false
		}
	});

	const emit = defineEmits(['click']);
</script>

<template>
	<button :class="buttonVariants({ variant, size, icon })" v-bind="props" @click="emit('click')">
		<slot />
	</button>
</template>

<style lang="postcss">
	.btn {
		@apply flex h-10 items-center justify-center rounded-full gap-2.5 px-6 py-2.5 text-sm transition-colors duration-200 disabled:cursor-not-allowed disabled:opacity-50;

		&.btn-primary {
			@apply bg-alabaster-950 text-white hover:bg-alabaster-950/80;
		}

		&.btn-secondary {
			@apply bg-alabaster-200 text-black hover:bg-alabaster-200/80;
		}

		&.btn-ghost {
			@apply bg-transparent text-alabaster-950 hover:bg-alabaster-950/10;
		}

		&.btn-large {
			@apply h-11 px-8 py-3 text-base;
		}

		&.btn-icon {
			@apply w-10 px-1 py-1 text-xl;

			&.btn-large {
				@apply w-11;
			}
		}
	}
</style>
