// resources/apps/admin/components/ui/checkbox/checkbox.vue
<script setup>
	import { cn } from '@/lib/utils';
	import { CheckboxIndicator, CheckboxRoot, useForwardPropsEmits } from 'radix-vue';
	import { computed } from 'vue';

	const props = defineProps({
		defaultChecked: { type: Boolean, required: false },
		checked: { type: [Boolean, String], required: false },
		disabled: { type: Boolean, required: false },
		required: { type: Boolean, required: false },
		name: { type: String, required: false },
		value: { type: String, required: false },
		id: { type: String, required: false },
		asChild: { type: Boolean, required: false },
		as: { type: null, required: false },
		class: { type: null, required: false },
	});
	const emits = defineEmits(['update:checked']);

	const delegatedProps = computed(() => {
		const { class: _, ...delegated } = props;

		return delegated;
	});

	const forwarded = useForwardPropsEmits(delegatedProps, emits);
</script>

<template>
	<CheckboxRoot
		v-bind="forwarded"
		:class="
			cn(
				'peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
				props.class,
			)
		"
	>
		<CheckboxIndicator class="text-current flex h-full w-full items-center justify-center">
			<slot>
				<i class="ri-check-line" />
			</slot>
		</CheckboxIndicator>
	</CheckboxRoot>
</template>

// resources/admin/components/ui/checkbox.tsx
import * as React from 'react';
import * as CheckboxPrimitive from '@radix-ui/react-checkbox';

import { cn } from '@/admin/lib/utils';

const Checkbox = ({ className, ...props }: React.ComponentProps<typeof CheckboxPrimitive.Root>) => {
	return (
		<div className="flex items-center justify-center">
			<CheckboxPrimitive.Root
				data-slot="checkbox"
				className={cn(
					'peer size-4 shrink-0 cursor-pointer border border-input bg-input/10 shadow-xs transition-shadow outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 data-[state=checked]:border-primary data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground dark:bg-input/30 dark:aria-invalid:ring-destructive/40 dark:data-[state=checked]:bg-primary',
					className,
				)}
				{...props}
			>
				<CheckboxPrimitive.Indicator
					data-slot="checkbox-indicator"
					className="flex items-center justify-center text-current transition-none"
				>
					<i className="hgi hgi-stroke hgi-tick-02 text-base/none font-extrabold" />
				</CheckboxPrimitive.Indicator>
			</CheckboxPrimitive.Root>
		</div>
	);
};

export { Checkbox };
