// resources/apps/admin/components/ui/dialog/dialog.vue
<script setup>
	import { DialogRoot, useForwardPropsEmits } from 'radix-vue';

	const props = defineProps({
		open: { type: Boolean, required: false },
		defaultOpen: { type: Boolean, required: false },
		modal: { type: Boolean, required: false },
	});
	const emits = defineEmits(['update:open']);

	const forwarded = useForwardPropsEmits(props, emits);
</script>

<template>
	<DialogRoot v-bind="forwarded">
		<slot />
	</DialogRoot>
</template>

<style lang="postcss">
	.dialog {
		@apply fixed left-1/2 top-1/2 z-50 grid w-full max-w-lg -translate-x-1/2 -translate-y-1/2 grid-rows-[auto_1fr_auto] rounded-md border border-border bg-popover shadow-lg duration-200;

		&[data-state='open'] {
			@apply animate-in fade-in-0 zoom-in-95 slide-in-from-left-1/2 slide-in-from-top-[48%];
		}

		&[data-state='closed'] {
			@apply animate-out fade-out-0 zoom-out-95 slide-out-to-left-1/2 slide-out-to-top-[48%];
		}

		.dialog-header {
			@apply flex items-center gap-2.5 border-b border-border px-4 py-2.5;
		}

		.dialog-content {
			@apply p-4;
		}

		.dialog-footer {
			@apply flex items-center gap-2.5 border-t border-border px-4 py-2.5;
		}
	}

	.dialog-overlay {
		@apply fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0;
	}

	.dialog-header {
		.dialog-title {
			@apply text-lg font-semibold leading-none tracking-tight;
		}

		.dialog-close {
			@apply ml-auto;
		}
	}
</style>

// resources/admin/components/ui/dialog.tsx
import * as React from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';

import { cn } from '@/admin/lib/utils';
import { Button } from './button';

const Dialog = ({ ...props }: React.ComponentProps<typeof DialogPrimitive.Root>) => {
	return <DialogPrimitive.Root data-slot="dialog" {...props} />;
};

const DialogTrigger = ({ ...props }: React.ComponentProps<typeof DialogPrimitive.Trigger>) => {
	return <DialogPrimitive.Trigger data-slot="dialog-trigger" {...props} />;
};

const DialogPortal = ({ ...props }: React.ComponentProps<typeof DialogPrimitive.Portal>) => {
	return <DialogPrimitive.Portal data-slot="dialog-portal" {...props} />;
};

const DialogClose = ({ ...props }: React.ComponentProps<typeof DialogPrimitive.Close>) => {
	return <DialogPrimitive.Close data-slot="dialog-close" {...props} />;
};

const DialogOverlay = ({
	className,
	...props
}: React.ComponentProps<typeof DialogPrimitive.Overlay>) => {
	return (
		<DialogPrimitive.Overlay
			data-slot="dialog-overlay"
			className={cn(
				'fixed inset-0 z-50 bg-black/50 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:animate-in data-[state=open]:fade-in-0',
				className,
			)}
			{...props}
		/>
	);
};

const DialogContent = ({
	className,
	children,
	...props
}: React.ComponentProps<typeof DialogPrimitive.Content>) => {
	return (
		<DialogPortal>
			<DialogOverlay />
			<DialogPrimitive.Content
				className={cn(
					'fixed inset-0 z-50 m-auto h-fit w-[90vw] max-w-xl divide-y divide-border border border-border bg-background text-primary data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95',
					className,
				)}
				{...props}
			>
				{children}
			</DialogPrimitive.Content>
		</DialogPortal>
	);
};

const DialogHeader = ({ className, ...props }: React.ComponentProps<'div'>) => {
	return (
		<div data-slot="dialog-header" className={cn('flex p-4 text-left', className)} {...props} />
	);
};

const DialogFooter = ({ className, ...props }: React.ComponentProps<'div'>) => {
	return (
		<div
			data-slot="dialog-footer"
			className={cn(
				'flex flex-col-reverse p-4 sm:flex-row sm:justify-end sm:space-x-2',
				className,
			)}
			{...props}
		/>
	);
};

const DialogTitle = ({
	className,
	...props
}: React.ComponentProps<typeof DialogPrimitive.Title>) => {
	return (
		<div className="flex items-center justify-between">
			<DialogPrimitive.Title
				className={cn(
					'inline-flex items-center gap-4 text-lg/none font-semibold tracking-tight',
					className,
				)}
				data-slot="dialog-title"
				{...props}
			/>
			<DialogClose asChild>
				<Button className="size-8" variant="ghost" size="icon">
					<i className="hgi hgi-stroke hgi-cancel-01 text-lg" />
				</Button>
			</DialogClose>
		</div>
	);
};

const DialogDescription = ({ className, ...props }: React.ComponentProps<'div'>) => {
	return (
		<div
			data-slot="dialog-description"
			className={cn('text-sm text-muted-foreground', className)}
			{...props}
		/>
	);
};

export {
	Dialog,
	DialogClose,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogOverlay,
	DialogPortal,
	DialogTitle,
	DialogTrigger,
};
