// resources/apps/admin/components/ui/label/label.vue
<script setup>
	import { Label } from 'radix-vue';

	import { cn } from '@/js/lib/utils';

	const { class: classes, ...props } = defineProps({
		for: { type: String, required: false },
		asChild: { type: Boolean, required: false },
		as: { type: null, required: false },
		class: { type: null, required: false },
	});
</script>

<template>
	<Label
		v-bind="props"
		:class="
			cn('text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70', classes)
		"
	>
		<slot />
	</Label>
</template>

// resources/admin/components/ui/label.tsx
import * as LabelPrimitive from '@radix-ui/react-label';
import * as React from 'react';

import { cn } from '@/admin/lib/utils';

export const Label = ({
	className,
	...props
}: React.ComponentProps<typeof LabelPrimitive.Root>) => {
	return (
		<LabelPrimitive.Root
			className={cn(
				'flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
				className,
			)}
			data-slot="label"
			{...props}
		/>
	);
};
